server:
  port: 8001
#redis连接配置
spring:
  redis:
    # 地址
    host: 123.249.33.96
    # 端口，默认为6379
    port: 6381
    # 数据库索引
    database: 0
    # 密码
    password: qiansl
    # 连接超时时间
    timeout: 100
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
